sudo: false
language: ruby
before_install:
  - if [[ $TRAVIS_RUBY_VERSION =~ ^(1|2\.[012]|jruby-1)\. ]]; then gem install rubygems-update --version '~> 2.7' --no-document && update_rubygems; elif [[ ! $TRAVIS_RUBY_VERSION =~ ^truffleruby- ]]; then gem update --system; fi
  - gem --version
  - if [[ $TRAVIS_RUBY_VERSION =~ ^(1|2\.[012]|jruby-1)\. ]]; then gem install bundler --version '~> 1.17'; else gem install bundler; fi
  - bundle --version
notifications:
  email:
    - john.crepezzi@gmail.com
    - andrew@avit.ca
branches:
  only:
    - master
rvm:
  - 1.9.3
  - 2.0
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - 2.4.0
  - ruby-head
env:
  - RAILS_VERSION='~> 3.2'
  - RAILS_VERSION='~> 4.2'
  - RAILS_VERSION='~> 5.0'
matrix:
  exclude:

    # Rails 5 only runs on ruby 2.3 and up
    - rvm: 1.9.3
      env: RAILS_VERSION='~> 5.0'
    - rvm: 2.0
      env: RAILS_VERSION='~> 5.0'
    - rvm: 2.1.10
      env: RAILS_VERSION='~> 5.0'
    - rvm: 2.2.6
      env: RAILS_VERSION='~> 5.0'

    # Rails 3 no longer runs on ruby 2.4 and up
    - rvm: 2.4.0
      env: RAILS_VERSION='~> 3.2'
    - rvm: ruby-head
      env: RAILS_VERSION='~> 3.2'
